# Generated by Django 5.1.2 on 2024-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='note',
            field=models.TextField(default=1, max_length=3000),
            preserve_default=False,
        ),
    ]
