# Generated by Django 5.1.2 on 2024-10-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_employee_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('question_name', models.CharField(max_length=255)),
                ('question_text', models.TextField(max_length=3000)),
                ('doctor', models.CharField(max_length=255)),
                ('answer', models.TextField(max_length=3000)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
