# Generated by Django 5.1.2 on 2024-10-30 20:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_alter_input_answer_alter_input_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
