# Generated by Django 5.1.2 on 2024-10-31 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_input_created_at'),
        ('topics', '0002_rename_input_topic_rename_topic_topic_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='question_topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='topics.topic'),
            preserve_default=False,
        ),
    ]
