# Generated by Django 5.1.2 on 2024-10-31 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Input',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='topic_name',
        ),
    ]
